# Generated by Django 3.1.6 on 2021-06-15 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordertrans',
            old_name='user',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='shipping',
            old_name='user',
            new_name='customer',
        ),
    ]
