# Generated by Django 3.1.6 on 2021-06-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0003_auto_20210615_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('customizable', 'customizable'), ('predesigned', 'designed')], max_length=15, null=True),
        ),
    ]
