# Generated by Django 3.1.6 on 2021-06-15 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0004_auto_20210615_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('c', 'customizable'), ('d', 'designed')], max_length=1, null=True),
        ),
    ]
