# Generated by Django 3.1.6 on 2021-06-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0006_auto_20210623_0114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
