# Generated by Django 3.1.6 on 2021-06-23 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0008_auto_20210623_0440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artPrice', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('artName', models.ImageField(upload_to='')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasashop.customer')),
            ],
        ),
    ]
