# Generated by Django 3.1.6 on 2021-06-23 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0009_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='artFile',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='entries',
            name='artName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
