# Generated by Django 3.1.6 on 2021-06-24 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0011_customer_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='entries',
            name='artBy',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='entries',
            name='artGcash',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
