# Generated by Django 3.1.6 on 2021-06-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0012_auto_20210624_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='artGcash',
            field=models.IntegerField(default=0),
        ),
    ]
