# Generated by Django 3.1.6 on 2021-06-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0014_auto_20210624_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='artGcash',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=11),
        ),
    ]
