# Generated by Django 3.1.6 on 2021-06-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0015_auto_20210624_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='artBy',
            field=models.CharField(max_length=50),
        ),
    ]
