# Generated by Django 3.1.6 on 2021-06-24 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0017_auto_20210624_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='artBy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
