# Generated by Django 3.1.6 on 2021-06-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0018_auto_20210624_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='Fname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='entries',
            name='artName',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
