# Generated by Django 3.1.6 on 2021-06-24 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0019_auto_20210624_0601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='device',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
