# Generated by Django 3.1.6 on 2021-06-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0020_auto_20210624_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entries',
            name='artFile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
