# Generated by Django 3.1.6 on 2021-06-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0023_auto_20210624_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Fname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='Lname',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
