# Generated by Django 3.1.6 on 2021-06-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0025_auto_20210624_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='customer',
        ),
    ]
