# Generated by Django 3.1.6 on 2021-06-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0026_remove_cartitem_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cdesign',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
