# Generated by Django 3.1.6 on 2021-06-25 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0028_auto_20210625_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cdesign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasashop.entries'),
        ),
    ]
