# Generated by Django 3.1.6 on 2021-06-25 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasashop', '0029_auto_20210625_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cdesign',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cdesign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasashop.entries'),
        ),
    ]
